In [11]:
import pandas as pd
import os

In [12]:
#Find the SA2 area name for each row in the ABS data set

abs_2017 = pd.read_csv('../data/curated/2017ABS_csv')
for i in range(len(abs_2017['SA2 Area Name'])):
    abs_2017['SA2 Area Name'][i] = abs_2017['SA2 Area Name'][i].split('summary_ ', 1)[-1].split(' SA2', 1)[0].upper()
    
    if '-' in abs_2017['SA2 Area Name'][i]:

        abs_2017['SA2 Area Name'][i] = abs_2017['SA2 Area Name'][i].replace(' -', '')


abs_sa2 =[]
for i in range(len(abs_2017['SA2 Area Name'])):
    abs_sa2.append(abs_2017['SA2 Area Name'][i].upper())


#area codes to drop so we can get more rows filled
drop_words = ['NORTH', 'SOUTH', 'EAST', 'WEST', '(VIC.)']

#This will make Keilor East and Keilor West both just Keilor
for i in range(len(abs_2017['SA2 Area Name'])):
    for word in drop_words:
        if word in abs_2017['SA2 Area Name'][i]:
            word = ' '+word
            abs_2017['SA2 Area Name'][i] = abs_2017['SA2 Area Name'][i].replace(word, '')

/var/folders/mc/_4clq8l155jdkpr2knhw_mw00000gn/T/ipykernel_27902/4189593754.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  abs_2017['SA2 Area Name'][i] = abs_2017['SA2 Area Name'][i].split('summary_ ', 1)[-1].split(' SA2', 1)[0].upper()
/var/folders/mc/_4clq8l155jdkpr2knhw_mw00000gn/T/ipykernel_27902/4189593754.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  abs_2017['SA2 Area Name'][i] = abs_2017['SA2 Area Name'][i].replace(' -', '')
/var/folders/mc/_4clq8l155jdkpr2knhw_mw00000gn/T/ipykernel_27902/4189593754.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  abs_2017['SA2 Area Name'][i] = abs_2017['SA2 Area Name'][i].replace(word, '')

In [13]:
#Find the SA2 area name for each row in the ABS data set

abs_2018 = pd.read_csv('../data/curated/2018ABS_csv')
for i in range(len(abs_2017['SA2 Area Name'])):
    abs_2018['SA2 Area Name'][i] = abs_2018['SA2 Area Name'][i].split('summary_ ', 1)[-1].split(' SA2', 1)[0].upper()
    
    if '-' in abs_2018['SA2 Area Name'][i]:

        abs_2018['SA2 Area Name'][i] = abs_2018['SA2 Area Name'][i].replace(' -', '')


abs_sa2 =[]
for i in range(len(abs_2018['SA2 Area Name'])):
    abs_sa2.append(abs_2018['SA2 Area Name'][i].upper())


#area codes to drop so we can get more rows filled
drop_words = ['NORTH', 'SOUTH', 'EAST', 'WEST', '(VIC.)']

#This will make Keilor East and Keilor West both just Keilor
for i in range(len(abs_2018['SA2 Area Name'])):
    for word in drop_words:
        if word in abs_2018['SA2 Area Name'][i]:
            word = ' '+word
            abs_2018['SA2 Area Name'][i] = abs_2018['SA2 Area Name'][i].replace(word, '')

/var/folders/mc/_4clq8l155jdkpr2knhw_mw00000gn/T/ipykernel_27902/2701880474.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  abs_2018['SA2 Area Name'][i] = abs_2018['SA2 Area Name'][i].split('summary_ ', 1)[-1].split(' SA2', 1)[0].upper()
/var/folders/mc/_4clq8l155jdkpr2knhw_mw00000gn/T/ipykernel_27902/2701880474.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  abs_2018['SA2 Area Name'][i] = abs_2018['SA2 Area Name'][i].replace(' -', '')
/var/folders/mc/_4clq8l155jdkpr2knhw_mw00000gn/T/ipykernel_27902/2701880474.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  abs_2018['SA2 Area Name'][i] = abs_2018['SA2 Area Name'][i].replace(word, '')

In [14]:
#Find the SA2 area name for each row in the ABS data set

abs_2019 = pd.read_csv('../data/curated/2019ABS_csv')
for i in range(len(abs_2019['SA2 Area Name'])):
    abs_2019['SA2 Area Name'][i] = abs_2019['SA2 Area Name'][i].split('summary_ ', 1)[-1].split(' SA2', 1)[0].upper()
    
    if '-' in abs_2019['SA2 Area Name'][i]:

        abs_2019['SA2 Area Name'][i] = abs_2019['SA2 Area Name'][i].replace(' -', '')


abs_sa2 =[]
for i in range(len(abs_2019['SA2 Area Name'])):
    abs_sa2.append(abs_2019['SA2 Area Name'][i].upper())


#area codes to drop so we can get more rows filled
drop_words = ['NORTH', 'SOUTH', 'EAST', 'WEST', '(VIC.)']

#This will make Keilor East and Keilor West both just Keilor
for i in range(len(abs_2019['SA2 Area Name'])):
    for word in drop_words:
        if word in abs_2019['SA2 Area Name'][i]:
            word = ' '+word
            abs_2019['SA2 Area Name'][i] = abs_2019['SA2 Area Name'][i].replace(word, '')

/var/folders/mc/_4clq8l155jdkpr2knhw_mw00000gn/T/ipykernel_27902/701255770.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  abs_2019['SA2 Area Name'][i] = abs_2019['SA2 Area Name'][i].split('summary_ ', 1)[-1].split(' SA2', 1)[0].upper()
/var/folders/mc/_4clq8l155jdkpr2knhw_mw00000gn/T/ipykernel_27902/701255770.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  abs_2019['SA2 Area Name'][i] = abs_2019['SA2 Area Name'][i].replace(' -', '')
/var/folders/mc/_4clq8l155jdkpr2knhw_mw00000gn/T/ipykernel_27902/701255770.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  abs_2019['SA2 Area Name'][i] = abs_2019['SA2 Area Name'][i].replace(word, '')

In [15]:
#Find the SA2 area name for each row in the ABS data set

abs_2020 = pd.read_csv('../data/curated/2020ABS_csv')
for i in range(len(abs_2020['SA2 Area Name'])):
    abs_2020['SA2 Area Name'][i] = abs_2020['SA2 Area Name'][i].split('summary_ ', 1)[-1].split(' SA2', 1)[0].upper()
    
    if '-' in abs_2020['SA2 Area Name'][i]:

        abs_2020['SA2 Area Name'][i] = abs_2020['SA2 Area Name'][i].replace(' -', '')


abs_sa2 =[]
for i in range(len(abs_2020['SA2 Area Name'])):
    abs_sa2.append(abs_2020['SA2 Area Name'][i].upper())


#area codes to drop so we can get more rows filled
drop_words = ['NORTH', 'SOUTH', 'EAST', 'WEST', '(VIC.)']

#This will make Keilor East and Keilor West both just Keilor
for i in range(len(abs_2020['SA2 Area Name'])):
    for word in drop_words:
        if word in abs_2020['SA2 Area Name'][i]:
            word = ' '+word
            abs_2020['SA2 Area Name'][i] = abs_2020['SA2 Area Name'][i].replace(word, '')

/var/folders/mc/_4clq8l155jdkpr2knhw_mw00000gn/T/ipykernel_27902/1409094192.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  abs_2020['SA2 Area Name'][i] = abs_2020['SA2 Area Name'][i].split('summary_ ', 1)[-1].split(' SA2', 1)[0].upper()
/var/folders/mc/_4clq8l155jdkpr2knhw_mw00000gn/T/ipykernel_27902/1409094192.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  abs_2020['SA2 Area Name'][i] = abs_2020['SA2 Area Name'][i].replace(' -', '')
/var/folders/mc/_4clq8l155jdkpr2knhw_mw00000gn/T/ipykernel_27902/1409094192.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  abs_2020['SA2 Area Name'][i] = abs_2020['SA2 Area Name'][i].replace(word, '')

In [30]:
wanted_features = ['Estimated resident population (no.)', 'Population density (persons/km2)', 'Median age - persons (years)', 'Working age population (aged 15-64 years) (no.)', 'Health care and social assistance (no.)', 'Financial and insurance services (no.)', 'Administrative and support services (no.)', 'Education and training (no.)', 'Accommodation and food services (no.)',
       'Public administration and safety (no.)','Value of residential building ($m)', 'Houses - total (no.)', 'Townhouses - total (no.)', 'Apartments - total (no.)', 'SA2 Area Name']
abs_filtered_2017 = abs_2017[wanted_features]
abs_filtered_2018 = abs_2018[wanted_features]
abs_filtered_2019 = abs_2019[wanted_features]
abs_filtered_2020 = abs_2020[wanted_features]

In [31]:
abs_filtered_2020 = abs_filtered_2020[abs_filtered_2020['SA2 Area Name']!= 'BAYSIDE SA3 20801.CSV']
abs_filtered_2017 = abs_filtered_2017[abs_filtered_2017['SA2 Area Name']!= 'BAYSIDE SA3 20801.CSV']
abs_filtered_2018 = abs_filtered_2018[abs_filtered_2018['SA2 Area Name']!= 'BAYSIDE SA3 20801.CSV']
abs_filtered_2019 = abs_filtered_2019[abs_filtered_2019['SA2 Area Name']!= 'BAYSIDE SA3 20801.CSV']

In [35]:
abs_filtered_2020

,Estimated resident population (no.),Population density (persons/km2),Median age - persons (years),Working age population (aged 15-64 years) (no.),Health care and social assistance (no.),Financial and insurance services (no.),Administrative and support services (no.),Education and training (no.),Accommodation and food services (no.),Public administration and safety (no.),Value of residential building ($m),Houses - total (no.),Townhouses - total (no.),Apartments - total (no.),SA2 Area Name
0,14542.0,2139.2,40.3,8773.0,49.0,43.0,47.0,17.0,35.0,6.0,32.0,5521.0,228.0,135.0,CROYDON
1,16162.0,4600.1,37.9,11435.0,149.0,53.0,52.0,35.0,71.0,3.0,41.0,3491.0,1529.0,1763.0,NORTHCOTE
2,10092.0,2132.7,34.7,7166.0,78.0,22.0,84.0,5.0,68.0,8.0,43.0,2697.0,867.0,371.0,SUNSHINE
3,17932.0,3872.2,35.7,12301.0,77.0,44.0,56.0,20.0,55.0,12.0,42.0,3621.0,3698.0,286.0,PASCOE VALE
4,17245.0,7145.2,34.0,13369.0,141.0,50.0,74.0,29.0,95.0,NaN,43.0,1247.0,1250.0,6826.0,ST KILDA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,13353.0,4151.7,33.1,10048.0,189.0,199.0,95.0,45.0,94.0,3.0,155.0,1329.0,746.0,4657.0,HAWTHORN
299,13828.0,2474.9,38.8,9137.0,55.0,25.0,58.0,12.0,38.0,NaN,6.0,4142.0,595.0,5.0,ENDEAVOUR HILLS
300,16378.0,2022.4,37.6,10610.0,87.0,30.0,50.0,13.0,44.0,3.0,34.0,5302.0,1302.0,509.0,CROYDON
301,8709.0,2194.5,34.0,5956.0,22.0,3.0,32.0,5.0,24.0,3.0,3.0,2638.0,113.0,117.0,CRAIGIEBURN CENTRAL
303,7975.0,1864.7,44.5,5108.0,147.0,74.0,35.0,21.0,22.0,3.0,21.0,2382.0,116.0,643.0,IVANHOE EAGLEMONT